<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->a($this->url->get("zzz_sample"), "Go Back") ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>Edit zzz_sample</h1>
</div>

<?php echo $this->getContent(); ?>

<form action="<?= $this->url->get('zzz_sample/save') ?>" class="form-horizontal" method="post">
    <div class="form-group">
    <label for="fieldZzzSampleId" class="col-sm-2 control-label">Zzz Of Sample</label>
    <div class="col-sm-10">
        <?= $this->tag->inputText("zzz_sample_id", $zzz_sample->zzz_sample_id, ["size" => 30, "class" => "form-control", "id" => "fieldZzzSampleId"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldZzzSampleCd" class="col-sm-2 control-label">Zzz Of Sample Of Cd</label>
    <div class="col-sm-10">
        <?= $this->tag->inputText("zzz_sample_cd", $zzz_sample->zzz_sample_cd, ["size" => 30, "class" => "form-control", "id" => "fieldZzzSampleCd"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldName" class="col-sm-2 control-label">Name</label>
    <div class="col-sm-10">
        <?= $this->tag->inputText("name", $zzz_sample->name, ["size" => 30, "class" => "form-control", "id" => "fieldName"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldKind" class="col-sm-2 control-label">Kind</label>
    <div class="col-sm-10">
        <?= $this->tag->inputText("kind", $zzz_sample->kind, ["class" => "form-control", "id" => "fieldKind"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldLockVersion" class="col-sm-2 control-label">Lock Of Version</label>
    <div class="col-sm-10">
        <?= $this->tag->inputNumeric("lock_version", $zzz_sample->lock_version, ["class" => "form-control", "id" => "fieldLockVersion"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldCreatedAt" class="col-sm-2 control-label">Created</label>
    <div class="col-sm-10">
        <?= $this->tag->inputText("created_at", $zzz_sample->created_at, ["size" => 30, "class" => "form-control", "id" => "fieldCreatedAt"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldCreatedBy" class="col-sm-2 control-label">Created Of By</label>
    <div class="col-sm-10">
        <?= $this->tag->inputText("created_by", $zzz_sample->created_by, ["size" => 30, "class" => "form-control", "id" => "fieldCreatedBy"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldUpdatedAt" class="col-sm-2 control-label">Updated</label>
    <div class="col-sm-10">
        <?= $this->tag->inputText("updated_at", $zzz_sample->updated_at, ["size" => 30, "class" => "form-control", "id" => "fieldUpdatedAt"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldUpdatedBy" class="col-sm-2 control-label">Updated Of By</label>
    <div class="col-sm-10">
        <?= $this->tag->inputText("updated_by", $zzz_sample->updated_by, ["size" => 30, "class" => "form-control", "id" => "fieldUpdatedBy"]) ?>
    </div>
</div>


    <?php echo $this->tag->inputHidden("id", $zzz_sample->zzz_sample_id) ?>

    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <?php echo $this->tag->inputSubmit("save", "Save", ['class' => "btn btn-primary"]) ?>
        </div>
    </div>
</form>
