<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->a($this->url->get("zzz_sample/index"), "Go Back"); ?></li>
            <li class="next"><?php echo $this->tag->a($this->url->get("zzz_sample/new"), "Create"); ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>Search result</h1>
</div>

<?php echo $this->getContent(); ?>

<div class="row">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Zzz Of Sample</th>
            <th>Zzz Of Sample Of Cd</th>
            <th>Name</th>
            <th>Kind</th>
            <th>Lock Of Version</th>
            <th>Created</th>
            <th>Created Of By</th>
            <th>Updated</th>
            <th>Updated Of By</th>

                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($page->getItems() as $zzz_sample): ?>
            <tr>
                <td><?php echo $zzz_sample->zzz_sample_id; ?></td>
            <td><?php echo $zzz_sample->zzz_sample_cd; ?></td>
            <td><?php echo $zzz_sample->name; ?></td>
            <td><?php echo $zzz_sample->kind; ?></td>
            <td><?php echo $zzz_sample->lock_version; ?></td>
            <td><?php echo $zzz_sample->created_at; ?></td>
            <td><?php echo $zzz_sample->created_by; ?></td>
            <td><?php echo $zzz_sample->updated_at; ?></td>
            <td><?php echo $zzz_sample->updated_by; ?></td>

                <td><?php echo $this->tag->a($this->url->get("zzz_sample/edit/" . $zzz_sample->zzz_sample_id), "Edit"); ?></td>
                <td><?php echo $this->tag->a($this->url->get("zzz_sample/delete/" . $zzz_sample->zzz_sample_id), "Delete"); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<div class="row">
    <div class="col-sm-1">
        <p class="pagination" style="line-height: 1.42857;padding: 6px 12px;">
            <?php echo $page->getCurrent(), "/", $page->getTotalItems() ?>
        </p>
    </div>
    <div class="col-sm-11">
        <nav>
            <ul class="pagination">
                <li><?php echo $this->tag->a($this->url->get("zzz_sample/search"), "First", ['class' => 'page-link', 'id' => 'first']) ?></li>
                <li><?php echo $this->tag->a($this->url->get("zzz_sample/search?page=" . $page->getPrevious()), "Previous", ['class' => 'page-link', 'id' => 'previous']) ?></li>
                <li><?php echo $this->tag->a($this->url->get("zzz_sample/search?page=" . $page->getNext()), "Next", ['class' => 'page-link', 'id' => 'next']) ?></li>
                <li><?php echo $this->tag->a($this->url->get("zzz_sample/search?page=" . $page->getLast()), "Last", ['class' => 'page-link', 'id' => 'last']) ?></li>
            </ul>
        </nav>
    </div>
</div>
